apiVersion: v1
kind: Service
metadata:
  annotations:
    service.protal.kubernetes.io/type: NodePort
  labels:
    app: mydeployment
  name: mysvcnodeport
  namespace: default
spec:
  ports:
  - name: service0
    nodePort: 32220   #Not required
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: myubuntu
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}

